### ISSUE TITLE
Programatically use controls

### ISSUE THREAD

**Issue by vinayakkulkarni** [korywka/mapbox-controls#30]
I propose adding a property to the controls as an option where user can programatically enable controls without the need of adding them on the map.
There's already a prop in mapbox-gl-draw which allows you to add DrawControl without adding the buttons as controls on the map – [displayControlsDefault](https://github.com/mapbox/mapbox-gl-draw/blob/main/docs/API.md#options)

<img width="376" alt="Screenshot 2021-05-20 at 4 33 03 PM" src="https://user-images.githubusercontent.com/19776877/118968029-0de98d00-b989-11eb-83f3-735009e7e37b.png">

**Comment by korywka** [comment]
Thanks, you can use programmatically (`measuringOn`, `measuringOff` methods), and hide it from the map just to set `display: none;` to `.mapbox-control-ruler` class. Thanks for proposal, let's see if someone else needs this option.

**Comment by kaareltinn** [comment]
Hey! I would also appreciate this option a lot. Makes it easier to add custom control buttons.

**Comment by korywka** [comment]
@kaareltinn Hi. Please wait till the war is over.

**Comment by korywka** [comment]
✅ https://www.npmjs.com/package/@mapbox-controls/ruler
