### ISSUE TITLE
Style control buttons have one rounded corner when focused

### ISSUE THREAD

**Issue by foundryspatial-duncan** [korywka/mapbox-controls#36]
The built-in mapbox-gl styles apply a border-radius to the first and last buttons in a control group:

```css
.mapboxgl-ctrl-group button:focus:first-child {...}
.mapboxgl-ctrl-group button:focus:last-child {...}
```

The style control's buttons are displayed horizontally so the top/bottom edge border radius doesn't apply here. (It's more visible if you change the `-active` color to something darker:

Here it is in the [docs' excample](https://korywka.github.io/mapbox-gl-controls/):
![Screenshot from 2021-11-25 16-04-41](https://user-images.githubusercontent.com/13056053/143509205-2bafa5e7-99e2-42ba-8bcb-e3ed026bd3cc.png)
![Screenshot from 2021-11-25 16-04-47](https://user-images.githubusercontent.com/13056053/143509209-4d25c420-4562-4d33-a4c5-f35ed0b06026.png)

Solution is to just override those styles. Here's what I did:

```scss
// scss
.mapbox-control-styles button {
    &, &:focus {
        border-radius: 0;
    }
}
```

**Comment by korywka** [comment]
✅ https://www.npmjs.com/package/@mapbox-controls/styles
