### ISSUE TITLE
Export the controls options interfaces

### ISSUE THREAD

**Issue by vcardins** [korywka/mapbox-controls#47]
It would be nice of the controls options interfaces were exported as well. I created a mapbox context where I encapsulate the map initialization. 
![image](https://user-images.githubusercontent.com/2383329/218608735-6b031402-dff9-45de-a019-e59abf8ffedb.png)

**Comment by vcardins** [comment]
I just found out that I can get a hold of the Controls' construtor parameters like: `ConstructorParameters<typeof RulerControl>;` which "solves" my problem, but it's more intuitive to import it directly.

**Comment by korywka** [comment]
Yep, you are right. Thanks. Should have been an update but russia destroyed my open source plans. Hopefully, will be in near future 🤝

**Comment by vcardins** [comment]
I'd be happy to submit a PR for this soon. Please, just let me know.

**Comment by korywka** [comment]
Yep, thanks.

**Comment by korywka** [comment]
✅ https://github.com/korywka/mapbox-controls/blob/master/packages/ruler/types/index.d.ts
