### ISSUE TITLE
Bug: When used with FullscreenControl, StyleControl buttons multiply

### ISSUE THREAD

**Issue by krvss** [korywka/mapbox-controls#49]
When I use the standard [FullscreenControl](https://docs.mapbox.com/mapbox-gl-js/api/markers/#fullscreencontrol), StyleControl buttons keep adding to the map as I switch between normal and Full-Screen modes.

**Comment by korywka** [comment]
A bit strange as it uses standard mapbox methods to add controls. Sounds like a bug in the `.addControl` call (e.g. wrong event listener).  if it is still relevant, please provide an example of the bug (https://codesandbox.io/s/vanilla-vanilla), I will reopen the ticket and try to fix.
