### ISSUE TITLE
Image delete button

### ISSUE THREAD

**Issue by mmc1718** [korywka/mapbox-controls#51]
Is there a way for the user to remove an image from the map once it has been added? A delete/trash button similar to the one found in the[ draw plug in](https://github.com/mapbox/mapbox-gl-draw/tree/main) could be useful. I would be happy to work on a PR if this is of interest.

**Comment by korywka** [comment]
@mmc1718 Thanks for the idea. I do not use this repo for work anymore, so I can't say anything about terms, but definitely sounds good to have and will implement.

**Comment by korywka** [comment]
<img width="48" alt="image" src="https://github.com/korywka/mapbox-controls/assets/988471/ff57cd37-9fdb-4ba7-99e0-fc7f390b6d3f">

if `removeButton` option is set to `true`, the button is visible instead of add button while an image is selected
