### ISSUE TITLE
Set mapbox-controls layer active on load

### ISSUE THREAD

**Issue by scotthubbert** [korywka/mapbox-controls#52]
This isn't an issue, but more so asking how you enabled the "Street" style and button by default on page load in the example page.

**Comment by korywka** [comment]
Hi. You can take a look at the example source code here:
https://github.com/korywka/mapbox-controls/blob/cdf6c96105c90d7ec1ca4b5382bf28875f93e2c3/preview/preview.js

Without parameters it adds control with `Street` and `Satellite` styles.
The current style is auto-selected.

You can also read docs for StyleControl here:
https://github.com/korywka/mapbox-controls/tree/master/packages/styles

Please let me know if you have any problems.

**Comment by scotthubbert** [comment]
I rebuilt from scratch and got the desired result. Thanks for responding so quickly.
