### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by jmowlaei** [korywka/mapbox-controls#54]
Error happen just for import :

`
import RulerControl from '@mapbox-controls/ruler';
import '@mapbox-controls/ruler/src/index.css';
`

> {
  "name": "plano",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@deck.gl/core": "^8.6.5",
    "@deck.gl/react": "^8.6.5",
    "@highcharts/map-collection": "^1.1.3",
    "@mapbox-controls/ruler": "^1.1.0",
    "@mapbox/mapbox-gl-geocoder": "^5.0.2",
    "@reduxjs/toolkit": "^1.5.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@turf/turf": "^6.5.0",
    "@uiw/react-codemirror": "^4.21.21",
    "ahooks": "^2.10.11",
    "antd": "^4.18.9",
    "axios": "^1.5.1",
    "codemirror": "^5.65.16",
    "craco-less": "^1.20.0",
    "deck.gl": "^8.6.5",
    "dexie": "^3.2.2",
    "file-saver": "^2.0.5",
    "highcharts": "^10.3.3",
    "highcharts-react-official": "^3.2.1",
    "immer": "^10.0.4",
    "joi": "^17.12.3",
    "js-file-download": "^0.4.12",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "mapbox-gl": "^3.2.0",
    "mathjax-full": "^3.2.0",
    "mathjax-react": "^2.0.1",
    "papaparse": "^5.4.1",
    "primeicons": "^6.0.1",
    "primereact": "^9.6.2",
    "prop-types": "^15.7.2",
    "qs": "^6.10.1",
    "react": "^17.0.2",
    "react-color": "^2.19.3",
    "react-contenteditable": "^3.3.6",
    "react-dom": "^17.0.2",
    "react-highlight-words": "^0.17.0",
    "react-hot-toast": "^2.1.1",
    "react-map-gl": "^6.1.18",
    "react-mathjax-preview": "^2.2.6",
    "react-redux": "^7.2.3",
    "react-router-dom": "^5.3.0",
    "react-scripts": "^4.0.3",
    "socket.io-client": "^4.2.0",
    "strftime": "^0.10.1",
    "tailwindcss-dir": "^4.0.0",
    "use-immer": "^0.9.0",
    "uuid": "^8.3.2",
    "xlsx": "^0.17.5",
    "zustand": "^4.5.1"
  },
  "scripts": {
    "start": "env-cmd -f .env.development craco start",
    "development": "craco start",
    "build": "env-cmd -f .env.production craco build",
    "test": "craco test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@craco/craco": "^6.4.3",
    "autoprefixer": "^9.8.8",
    "env-cmd": "^10.1.0",
    "postcss": "^7.0.39",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.17",
    "webpack": "^4.47.0"
  }
}

Failed to compile.

./node_modules/@mapbox-controls/ruler/src/index.js 64:7
Module parse failed: Unexpected token (64:7)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     }
|   }
>   draw = () => {
|     if (!this.map) throw Error('map is undefined');
|     this.map.addSource(lineLayer.source, {

**Comment by korywka** [comment]
Mapbox Controls code is native ES code that executes in all modern browsers without any babel. If your parser (babel) doesn't support native javascript, it is up to you to polyfill it. Something like https://babeljs.io/docs/babel-plugin-transform-class-properties/ can help.
